steps:
  - name: node:16
    entrypoint: npm
    args: ["install"]
  - name: node:16
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - 'MONGO_URL=${_MONGO_URL}'
      - 'PORT=${_PORT}'
      - 'JWTKEY=${_JWTKEY}'
  - name: node:16
    entrypoint: npm
    args: ["run", "build"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud config set app/cloud_build_timeout 16000&& gcloud app deploy",
      ]
timeout: "16000s"
options:
  logging: CLOUD_LOGGING_ONLY
